### YamlMime:Architecture
metadata:
  title: Microsoft Entra security for AWS
  titleSuffix: Azure Architecture Center
  description: Learn how Microsoft Entra ID can help secure and protect Amazon Web Services (AWS) identity management and account access. Discover Microsoft security solutions.
  author: martinekuan
  ms.author: architectures
  ms.date: 07/28/2022
  ms.reviewer: ssumner
  ms.topic: reference-architecture
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.custom:
    - fcp
  keywords:
    - Azure active directory
    - aws identity management
    - identity protection
    - Microsoft security solutions
name: Microsoft Entra identity management and access management for AWS
azureCategories:
  - identity
summary: Learn how Microsoft Entra ID can help secure and protect Amazon Web Services (AWS) identity management and account access. Discover Microsoft security solutions.
products:
  - azure
  - entra-id
thumbnailUrl: /azure/architecture/browse/thumbs/azure-aws-integration.png
content: |
   [!include[](aws-azure-ad-security-content.md)]
