### YamlMime:Architecture
metadata:
  title: Automated API deployments using APIOps
  titleSuffix: Azure Architecture Center
  description: Use APIOps with an Azure API Management instance to build and deploy APIs. This solution provides self-service tools, auditing, policy enforcement, and early feedback.
  author: rishabhsaha
  ms.author: risaha
  ms.date: 09/08/2022
  ms.reviewer: ssumner
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.custom: arb-devops
azureCategories:
  - devops
  - developer-tools
  - management-and-governance
products:
  - azure-api-management
  - azure-devops
  - azure-pipelines
name: Automate API deployments with APIOps
summary: Use APIOps with an API Management instance to build and deploy APIs. This solution provides self-service tools, auditing, policy enforcement, and early feedback.
thumbnailUrl: /azure/architecture/browse/thumbs/automated-api-deployments-architecture-diagram-thumb.png
content: |
  [!include[](automated-api-deployments-apiops-content.md)]
