### YamlMime:Architecture
metadata:
  title: Microsoft Entra IDaaS in security operations
  titleSuffix: Azure Architecture Center
  description: Learn how security operations teams can use Microsoft Entra identity and access features in an adaptive, integrated zero-trust security architecture.
  author: martinekuan
  ms.author: pnp
  ms.date: 08/23/2022
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.category:
    - security
  ms.custom:
    - fcp
    - example-scenario
name: Microsoft Entra IDaaS in security operations
azureCategories:
  - security
summary: Learn how security operations teams can use Microsoft Entra identity and access features in an adaptive, integrated zero-trust security architecture.
products:
  - entra-id
  - microsoft-sentinel
thumbnailUrl: /azure/architecture/browse/thumbs/architecture.png
content: |
   [!include[](azure-ad-security-content.md)]
